apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  type: ClusterIP
  selector: 
    app: db
  ports:
    - port: 8080 # pod/container port
      targetPort: 80 # Pod/container port    
    - port: 9000 # Service port
      targetPort: 3000 # pod/container port