apiVersion: v1
kind: Pod
metadata: 
  name: my-web-app
  labels: 
    app: db
spec: 
  containers: 
    - name: my-nginx-app
      image: raneem123/nginx-test 
      imagePullPolicy: IfNotPresent 
      ports: 
        - containerPort: 5000

